### ISSUE TITLE
[EPIC] Secret Handling

### ISSUE THREAD

**Issue by sylus** [StatCan/aaw-kubeflow-manifests#131]
## Overview

Even though some components that have secrets are merged in. This section is just to highlight some of the secret interpolation handling we still have to do and not forget about.

- #115 (`configmap`)

**Comment by blairdrummond** [comment]
Where secrets like this are needed, I think it might not be crazy just to create them in terraform. What do you think @sylus ?

**Comment by sylus** [comment]
Yeah so i run this kustomize and then afterwards I apply this configmap manually but argo can do it and will ignore this confgmap on future syncs.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-authservice-parameters
  namespace: istio-system
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
```
