### ISSUE TITLE
Failed to call `kfp.Client()` in jupyter notebook

### ISSUE THREAD

**Issue by rohank07** [StatCan/aaw-kubeflow-manifests#153]
Unable to call kfp.Client()
![image](https://user-images.githubusercontent.com/28408586/153285054-de986ad3-1d25-4767-9017-ca65621085a4.png)

We would have to use access-ml-pipeline PodDefault (https://github.com/canonical/bundle-kubeflow/issues/423)

```
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: access-ml-pipeline
  namespace: "<YOUR_USER_PROFILE_NAMESPACE>"
spec:
  desc: Allow access to Kubeflow Pipelines
  selector:
    matchLabels:
      access-ml-pipeline: "true"
  volumes:
    - name: volume-kf-pipeline-token
      projected:
        sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 7200
              audience: pipelines.kubeflow.org      
  volumeMounts:
    - mountPath: /var/run/secrets/kubeflow/pipelines
      name: volume-kf-pipeline-token
      readOnly: true
  env:
    - name: KF_PIPELINES_SA_TOKEN_PATH
      value: /var/run/secrets/kubeflow/pipelines/token
```
Using PodDefault https://www.kubeflow.org/docs/components/pipelines/sdk/connect-api/#multi-user-mode
Waiting for https://github.com/kubeflow/pipelines/pull/6629/files to be merged (pipelines-profile-controller needs PodDefault updates)
